#!/bin/bash

LANG=C
RED=`tput setaf 1`
GREEN=`tput setaf 2`
RST=`tput sgr0`

setup()
{
	local dist=$1
	echo -e "${GREEN}$PRETTY_NAME detected${RST}"
	export DIST_ROOT=./dist/$dist
	source $DIST_ROOT/setup.sh
}

unrecg_distro()
{
	echo -e "${RED}error: Unrecognized Distribution${RST}"
}

RELEASE_FILE=/etc/os-release

if [ -f "$RELEASE_FILE" ]; then
	DIST=$(grep NAME $RELEASE_FILE -w | sed -n 's/NAME=//p' | tr -d '"')
	PRETTY_NAME=$(grep PRETTY_NAME $RELEASE_FILE -w | sed -n 's/PRETTY_NAME=//p' | tr -d '"')
fi

case "$DIST" in
	Fedora|Ubuntu)
		setup $DIST
		;;
	*)
		unrecg_distro
		exit 1
		;;
esac
